version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    assignees:
      - T-Fowl
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - T-Fowl